### ISSUE TITLE
[BUG] UID/GID set above 100k

### ISSUE THREAD

**Issue by IvoMajic** [linuxserver/docker-kavita#2]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It seems one (at least /app/kavita/API.deps.json) or more files have its UID/GUI set above 100k (UID 197609, GID 197121) preventing Lchown from working correctly in environments such as LXC. So far I have not noticed this behavior in any other LSIO container image. The error can be observed during image pull:

` failed to register layer: failed to Lchown "/app/kavita/API.deps.json" for UID 197609, GID 197121 (try increasing the number of subordinate IDs in /etc/subuid and /etc/subgid): lchown /app/kavita/API.deps.json: invalid argument
`

### Expected Behavior

The image is pulled correctly

### Steps To Reproduce

1. Invoke `docker pull lscr.io/linuxserver/kavita:latest` in an LXC environment

### Environment

```markdown
- OS: Ubuntu Server 23.04, LXC image is Debian 12
- How docker service was installed: distro's packagemanager
```

### CPU architecture

x86-64

### Docker creation

```bash
docker pull lscr.io/linuxserver/kavita:latest
```

### Container logs

```bash
No logs as the image is not even pulled correctly
```

**Comment by aptalca** [comment]
That is an issue with your system and docker install, not this image. I don't believe there is such a thing as `[one] or more files have its UID/GUI set above 100k`. What you're referring to is uid remapping by your host kernel.

We don't support userns remapping, rootless docker or running docker in lxc.

Proxmox (most if not all lxc-docker issues we see are from proxmox users) devs also recommends against using docker in lxc.

Reference: https://www.reddit.com/r/MeshCentral/comments/10vk3bq/issue_installing_fresh_with_docker_using/

**Comment by IvoMajic** [comment]
Ok well at least it is documented now here if someone else stumbles on the same issue. The original Kavita image is still maintained and works in LXC, so not a big deal.

Rootless/LXC support is a matter of policy, which I was not aware of.

**Comment by aptalca** [comment]
Disregard my previous comment.

Inside the container, I see that _all_ the kavita app files are owned by `197609:197121`, which is not something we touch, but comes from the tarball we ingest from the upstream repo. We simply pull it in and untar into that folder.

It's not necessarily uid remapping, however, it seems your system (likely lxc) can't handle uids larger than 100,000. That might be something you can fix on your end (my bare metal docker install on various OSes don't have any such issues), but I'll also look into chowning the app folder during build time to something in the lower range and hope that it remediates the issue for everyone.

**Comment by IvoMajic** [comment]
Thank you for confirming my app files suspicion @aptalca , I was about to check if I can somehow mitigate that eg. my limitation in the mapping. But if we can fix it for everyone that would be great.

**Comment by aptalca** [comment]
@IvoMajic can you give this PR test image a try and let us know?
`lspipepr/kavita:amd64-v0.7.7-pkg-c3b466b4-dev-19dd104976da6e48e99348c434a47598824a8966-pr-3`

Thanks

**Comment by IvoMajic** [comment]
@aptalca tried it, pulls, and starts without issue now. I even managed to restore my old install backup into the LSIO container. Thank you very much.
